export const data = [
  {
    id: 1,
    name: 'faris',
    title: 'title here',
    note: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley",
    color: '#274059',
  },
  {
    id: 2,
    name: 'faris',
    title: 'title here title here title here',
    note: " Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley",
    color: '#DF4E58',
  },
  {
    id: 3,
    name: 'faris',
    title: 'title here',
    note: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley",
    color: '#F6F3EB',
  },
  {
    id: 4,
    name: 'faris',
    title: 'title here',
    note: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley",
    color: '#F5C4C0',
  },
  {
    id: 5,
    name: 'faris',
    title: 'title here',
    note: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley",
    color: '#F9F9F9',
  },
  {
    id: 6,
    name: 'faris',
    title: 'title here',
    note: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley",
    color: '#274059',
  },
  {
    id: 7,
    name: 'faris',
    title: 'title here',
    note: 'when an unknown printer took a galley',
    color: '#DF4E58',
  },
  {
    id: 8,
    name: 'faris',
    title: 'title here',
    note: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley",
    color: '#F6F3EB',
  },
  {
    id: 6,
    name: 'faris',
    title: 'title here',
    note: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley",
    color: '#274059',
  },
  {
    id: 7,
    name: 'faris',
    title: 'title here',
    note: 'when an unknown printer took a galley',
    color: '#DF4E58',
  },
  {
    id: 8,
    name: 'faris',
    title: 'title here',
    note: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley",
    color: '#F6F3EB',
  },
];
